### ISSUE TITLE
Divide by Zero

### ISSUE THREAD

**Issue by tgb20** [keshrath/ImageLoader#3]
When using the example
```
import at.mukprojects.imageloader.*;
import at.mukprojects.imageloader.gif.*;
import at.mukprojects.imageloader.giphy.*;

GifLoader loader;
GifList list;
PImage[] imgs;
int index;

void setup() {
  size(800, 450);
  frameRate(25);

  loader = new GiphyLoader(this, "dc6zaTOxFJmzC");
  list = loader.start("cat", false, 60 * 1000);

  index = 0;
}

void draw() {
  if (imgs == null) {
    if (list.size() > 0) {
      imgs = list.getRandom().getGifFrames();
    }
  } else {
    image(imgs[index], 0, 0, width, height);
    index++;
    if (index > imgs.length - 1) {
      index = 0;
    }
  }
}

void mousePressed() {
  imgs = list.getRandom().getGifFrames();
  index = 0;
}
```

You get a divide by zero error when it trys to getGifFrames()

**Comment by keshrath** [comment]
Hello,
thx for the info :) It seems that the Giphy API returns now a URL which the decoder cant decode. I will look into it and will hopefully be able to fix the issue soon.

**Comment by InteractivePrototyping** [comment]
Hello, Is there any update on how to fix this issue? Thanks

**Comment by mujina93** [comment]
Hello, I got the same error when trying to use Giphy. With the debugger on I get:
```
java.lang.ArithmeticException: / by zero
	at at.mukprojects.imageloader.gif.GifData.loadGif(Unknown Source)
	at at.mukprojects.imageloader.gif.GifData.getGifFrames(Unknown Source)
	at sketch_190701a.draw(sketch_190701a.java:69)
	at processing.core.PApplet.handleDraw(PApplet.java:2475)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
```
